### ISSUE TITLE
Asking Video Tutorial

### ISSUE THREAD

**Issue by rklamundao1** [Ascor8522/MetroDreamin-to-KML#1]
Regarding on installation of MetroDreamin KML, could you please provide us a video tutorial on how to do it as I am starting to learn IT? Thank you.

**Comment by Ascor8522** [comment]
All the useful info is provided in the [README.md](https://github.com/Ascor8522/MetroDreamin-to-KML/blob/master/README.md) file, including the installation instructions.
You just have to read.
