### ISSUE TITLE
No file result shown.

### ISSUE THREAD

**Issue by rklamundao1** [Ascor8522/MetroDreamin-to-KML#2]
Regarding the tool I use to expoert the MetroDreamin maps into KML  with the link attached on the side, https://github.com/Ascor8522/MetroDreamin-to-KML/blob/master/README.md, I tried to install that through Deno Command. However, I tried to follow the instruction but it is still not working. What shall I do? Please help me. Thank you! 
![image](https://github.com/Ascor8522/MetroDreamin-to-KML/assets/147981972/0ecce8ef-9c4f-4435-9ce0-4647d3419a24)

**Comment by Ascor8522** [comment]
Thank you for showing interest in my project.

Now, to answer your question, **you are running the command in the wrong place**.
You should be running it **from your terminal**, not from within the Deno REPL.

Everything should be very well explained in the [README.md](https://github.com/Ascor8522/MetroDreamin-to-KML/blob/master/README.md).
Please read it more carefully.
Do not hesitate to use your favorite search engine to look up the problems you're having next time.

Also, please **only report actual bugs** with the code or more advanced questions.
This is a "serious" project, where I assume the contributors and users have some prior knowledge with the tools that are used in this project.
**This project is not meant to teach the beginners how to use the terminal or Deno and to solve the issues they are having.**
